name: Verify

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Verify dependencies
        run: go mod verify
      
      - name: Set up golint
        run: go install golang.org/x/lint/golint@latest
      
      - name: Lint
        run: golint ./...
